### ISSUE TITLE
May 30, 2022 ... Less Secure App Access Disabled

### ISSUE THREAD

**Issue by pndaly** [thevickypedia/gmail-connector#3]
Hi,

In the past I have used my own code to send gmail from within Python using smtplib. Recently, this stopped working and 
I discovered that Google doesn't like apps that sign in using just user/pass ... they now prefer 2-factor authentication. This
is not possible for my application but they did allow "Less Secure App Access" to be enabled. Now, however, Google is
dropping support for this on May 30, 2022. At that time, my app will stop  working again.

Does/Will gmail-connector handle this problem? TIA.

**Comment by thevickypedia** [comment]
Unfortunately not. Since `gmail-connector` depends on google's smtp host, the authentication is handled by google itself.
However to avoid using "Less Secure App Access" you can generate app specific passwords at https://myaccount.google.com/intro/security OR https://myaccount.google.com/apppasswords
I have been using app specific passwords and it works as it should. It still requires an MFA configuration but the password will be a token generated by google and doesn't actually require two step verification when you use it in the code.

**Comment by thevickypedia** [comment]
Closing as stale
